2018-03-30 13:43:46,724 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6OCwiZXhwIjoxNTIyNDA3MTkwLjc0MTI0NzR9.dyIGe_SeBSsGAsmVR8dEAUiyZW7vyZ1lrozWMFJ7h-8 [GET] [in /home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: reset_password() got an unexpected keyword argument 'token'
2018-03-30 13:43:48,784 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6OCwiZXhwIjoxNTIyNDA3MTkwLjc0MTI0NzR9.dyIGe_SeBSsGAsmVR8dEAUiyZW7vyZ1lrozWMFJ7h-8 [GET] [in /home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: reset_password() got an unexpected keyword argument 'token'
2018-03-30 13:43:50,826 ERROR: Exception on /reset_password/eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNldF9wYXNzd29yZCI6OCwiZXhwIjoxNTIyNDA3MTkwLjc0MTI0NzR9.dyIGe_SeBSsGAsmVR8dEAUiyZW7vyZ1lrozWMFJ7h-8 [GET] [in /home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dmitry/code/python/Flask/first/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: reset_password() got an unexpected keyword argument 'token'
2018-03-30 14:14:38,538 INFO: Microblog startup [in /home/dmitry/code/python/Flask/first/ap/__init__.py:44]
2018-03-30 14:49:46,811 INFO: Microblog startup [in /home/dmitry/code/python/Flask/first/ap/__init__.py:44]
